ci:
  autoupdate_schedule: quarterly

default_stages: [commit]

repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.3
    hooks:
      - id: shellcheck
        # docs: https://github.com/koalaman/shellcheck/wiki
        # -x/--external-sources: Allow 'source' outside of FILES
        args: [-x, --shell=bash]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        args: [--disable, MD013, MD033, MD041, '--']


  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        args: [--ignore-words-list, iterm]
