ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    - id: shellcheck  # docs: https://github.com/koalaman/shellcheck/wiki
      # -x/--external-sources: Allow 'source' outside of FILES
      args: [-x, --shell=bash]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    - id: markdownlint
      args: [-r, '~MD013,~MD002']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      args: [--ignore-words-list, iterm]
